Add `playback-ids` route
muxinc/mux-elixir pull request #26
Opened 2021-04-29 20:40 UTC by alexdechaves

This PR adds the new `playback-ids` route: https://docs.mux.com/api-reference/video#operation/get-asset-or-livestream-id as well as rearranges the Assets module to now include the handling of Assets' playback IDs which may break some things

2021-05-03 20:24 UTC, jsanford8 requested changes

2021-05-03 20:24 UTC, jsanford8 commented on lib/mux/video/assets.ex
> +      #{inspect(Fixtures.asset(:create))}
should be a playback ID

2021-05-03 20:24 UTC, jsanford8 commented on lib/mux/video/assets.ex
> +      #{inspect(Fixtures.asset(:create))}
update this too

2021-05-03 20:24 UTC, jsanford8 commented on lib/mux/support/fixtures.ex
> +  def identifier do
maybe rename `playback_id_full`

2021-05-06 04:48 UTC, jsanford8 commented on test/mux/video/assets_test.exs
> +              "video/v1/assets/00ecNLnqiG8v00TLqqeZ00uCE5wCAaO3kKc/playback-ids/FRDDXsjcNgD013rx1M4CDunZ86xkq8A02hfF3b6XAa7iE"
You need a `/` in the front of the string literal here to match the mock. `"/video/v1` not `"video/v1`

2021-05-06 04:48 UTC, jsanford8 commented on lib/mux/video/assets.ex
> +      iex> {:ok, playback_id, _env} = Mux.Video.Assets.get_playback_id(client, "00ecNLnqiG8v00TLqqeZ00uCE5wCAaO3kKc", "FRDDXsjcNgD013rx1M4CDunZ86xkq8A02hfF3b6XAa7iE")
So this line is failing because there is no mocked request for this call. See the comment below in the mocks around missing a leading `/`

2021-05-06 04:48 UTC, jsanford8 commented on lib/mux/video/assets.ex
> +      iex> {:ok, playback_id, _env} = Mux.Video.Assets.create_playback_id(client, "00ecNLnqiG8v00TLqqeZ00uCE5wCAaO3kKc", %{policy: "public"})
I'm not sure why this one is failing, but the first thing that comes to mind is that maybe the mock is matching at the wrong place. Let's chat about this one Thursday, we can figure it out together.

2021-05-06 22:06 UTC, jsanford8 approved these changes

2021-05-06 22:06 UTC, jsanford8 commented
All that's left is bumping the version - I think we need to major version bump with some release notes based on the breaking API changes (things moving around)

2021-05-11 01:54 UTC, jsanford8 commented
@alexdechaves - Let me know what you need to get this released so we can get it out the door

2021-06-04 21:13 UTC, alexdechaves commented
@dylanjha I believe this is all good before merging (before resolving the conflicts)

2021-06-04 21:17 UTC, merged